# Generated by Django 2.2 on 2024-09-17 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Customers',
        ),
    ]
