# Generated by Django 2.2 on 2024-09-18 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0002_auto_20240917_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albums',
            old_name='drive',
            new_name='name',
        ),
        migrations.AddField(
            model_name='albums',
            name='path',
            field=models.CharField(default='<django.db.models.fields.CharField>\\', max_length=255),
        ),
        migrations.AddField(
            model_name='albums',
            name='share',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='albums',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='pics.Customers'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pics.Customers'),
        ),
    ]
