# Generated by Django 2.2 on 2024-09-18 04:59

from django.db import migrations, models
import pics.models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0003_auto_20240918_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='image_url',
        ),
        migrations.AddField(
            model_name='photo',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=pics.models.uploadto),
        ),
    ]
