# Generated by Django 2.2 on 2024-09-18 08:28

from django.db import migrations, models
import pics.models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0004_auto_20240918_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to=pics.models.uploadto),
        ),
    ]
