# Generated by Django 2.2 on 2024-09-20 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0005_auto_20240918_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavAlbums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorited_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='pics.Albums')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_albums', to='pics.Customers')),
            ],
            options={
                'unique_together': {('user', 'album')},
            },
        ),
    ]
